use_frameworks!

platform :ios, '9.0'

target 'PrivateHelloWorld_Example' do
  pod 'PrivateHelloWorld', :path => 'https://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@github.com/wei3527722/PrivateHelloWorld.git'
end
